name: VK Parser CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 12 * * *'  # Запускать каждый день в 12:00 по UTC (15:00 по Москве)

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --no-root

      # Добавьте этот шаг для запуска скрипта:
      - name: Run VK Spam Bot
        run: poetry run python vk_spam_bot-main/sendler.py
        env:
          ACCESS_TOKEN_1: ${{ secrets.ACCESS_TOKEN_1 }}
          ACCESS_TOKEN_2: ${{ secrets.ACCESS_TOKEN_2 }}
          ACCESS_TOKEN_3: ${{ secrets.ACCESS_TOKEN_3 }}


      - name: Backup database
        run: |
          mkdir -p backups
          if [ -f users.db ]; then
            cp users.db backups/users_backup_$(date +%Y%m%d_%H%M%S).db
          else
            echo "Файл users.db не найден. Пропускаем резервное копирование."
          fi

      - name: Upload backup
        uses: actions/upload-artifact@v2
        with:
          name: db-backup
          path: backups/

      - name: Upload cash files
        uses: actions/upload-artifact@v4
        with:
          name: cash-files
          path: vk_spam_bot-main/cash/


        env:
          ACCESS_TOKEN_1: ${{ secrets.ACCESS_TOKEN_1 }}
          ACCESS_TOKEN_2: ${{ secrets.ACCESS_TOKEN_2 }}
          ACCESS_TOKEN_3: ${{ secrets.ACCESS_TOKEN_3 }}